import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { appRoutes } from './app.module.routes';

import { ClickOutside } from './directives/lnv-click-outside.directive'
import { mobileCollapse } from './directives/sidenav-collapse-on-mobile'

import { AppComponent } from './components/app/app.component';

import {
	HomeComponent,
	PhoneCallComponent,
	PageErrorComponent,
	Page404Component,
	LoginShellComponent,
	HLoaderComponent,
	ContactSearchModalComponent,
	CapturePhotoModalComponent,
	UploadPhotoMenuComponent,
	CallFailureModalComponent,
	DashboardHomeComponent,
	MaterialAlertComponent,
	MaterialActionAlertComponent,
	MaterialSnackBarComponent,
	PbxRepLinesComponent,
	CompanyComponent,
	EmployeesComponent,
	PbxLinesComponent,
	CompanyOverviewComponent,
	CreateCompanyComponent,
	CreatePbxLineComponent,
	InviteEmployeeComponent,
	CallQueueComponent,

	PbxLineCallComponent,
	PbxLineVideoComponent,
	PbxLineChatComponent,
	PbxLineQueueComponent,
	PbxLineInformationComponent,
	PbxCustomerComponent,

	PbxSearchBoxComponent,
	PbxSearchComponent,
	PbxRepShellComponent,
	PbxEmployersComponent,

	OutgoingCallDialogComponent,
	EmployeeCompaniesComponent,
	ShowFormErrorsComponent,
	MemberLoginFormComponent,
	GuestLoginFormComponent,
	RegisterFormComponent,
	FooterComponent,
	ProfileSummaryComponent,
	NavMenuComponent,
	ContactUsFormComponent,
	ContactComponent,
	ContactListComponent,
	ButtonAddContactComponent,
	SidenavToggleComponent,
	FormAddContactComponent,
	ImageSelectorComponent,
	PhotoCameraComponent,
	FormEditContactComponent,
	ContactCardComponent,
	IdCardComponent,
	IncomingPhoneCallComponent,
	PhoneListenerComponent,
	GlobalListenerComponent,
	GlobalPhoneListenerComponent,
	FormCreateCompanyComponent,
	FormEditCompanyComponent,
	CompanyLocationsComponent,
	CompanyPbxlineDetailsComponent,
	CompanyPbxlineRepsComponent,
	CompanyPhotosComponent,
	CompanyVideosComponent,
	EmployerAssignedPbxlineComponent,
	EmployerDetailsComponent,
	FormCompanyEmployeeAddComponent,
	FormCompanyEmployeeEditComponent,
	FormCompanyEmployeeInviteAddComponent,
	FormCompanyEmployeeInviteEditComponent,
	FormCompanyLocationAddComponent,
	FormCompanyPbxlineAddComponent,
	FormCompanyPbxlineEditComponent,
	FormCompanyPhotoAddComponent,
	FormCompanyVideoAddComponent,
	FormCompanyPbxlineRepAddComponent,
	CompanyPhotoComponent,
	ButtonAddCompanyPhotoComponent,
	FormCompanyLocationEditComponent,
	ButtonAddCompanyLocationComponent,
	ButtonAddCompanyVideoComponent,
	ButtonAddEmployeeInviteComponent,
	ButtonAddPbxlineComponent,
	CompanyLocationComponent,
	CompanyPbxlineComponent,
	EmployeeCardComponent,
	CompanyEmployeeInviteComponent,
	CompanyEmployeeComponent,
	PublicPbxlineComponent,
	PhoneRingerComponent,
	TextMessagingComponent,
	TextMessagingMessageComponent,
	PrivateMessagingComponent,
	PbxCustomerDetailsComponent,
	OtherRepsComponent,
	OtherRepComponent,
	FormGetInfoComponent,
	MeetingAttendeeComponent,
	FormAddAttendeeComponent,
	MeetingItemComponent,
	FormEditMeetingComponent,
	MeetingDetailsComponent,
	MeetingInviteComponent,
	LoginOptionsComponent,
	FormNetcastAddComponent,
	FormNetcastEditComponent,
	ButtonAddNetcastComponent,
} from "./components/index";

import {
	CompanyEmployeeDetailsPage,
	CustomerPbxPage,
	RepPbxPage,
	MyCompanyPage,
	CompanyEditPage,
	DashboardPage,
	CompanyPbxlinesPage,
	CompanyEmployeesPage,
	CompanyEmployeeInvitesPage,
	RegisterPage,
	LoginPage,
	CompanyProfilePage,
	SettingsPage,
	AccountPage,
	MyEmployersPage,
	ContactsPage,
	ContactUsPage,
	PublicUserProfilePage,
	LoginHelpPage,
	LogoutPage,
	PhonePage,
	BlockListPage,
	CompanyCreatePage,
	EmployerAssignedPbxlinesPage,
	CompanySearchPage,
	GuestAccountPage,
	ManageMeetingsPage,
	MeetingsPage,
	MeetingInvitesPage,
	CreateMeetingPage,
	MeetingPage,
	MeetingsDashboardPage,
	PastMeetingsPage,
	NetcasterPage,
	NetcasteePage,
	NetcastListPage,
	NetcastSearchPage,
	NetcastDashboardPage,
	NetcastDetailsPage,
	ErrorPage,
} from "./pages/index";

import { FileNamePipe } from './pipes/filename.pipe';
import { PbxLineOutgoingCallDialog } from './components/pbx-line/pbx-line-outgoing-call-dialog/pbx-line-outgoing-call-dialog.component';

export const sharedConfig: NgModule = {
	bootstrap: [AppComponent],
	declarations: [ // items pages and components that are not loaded dynamically
		AppComponent,
		HomeComponent,
		PhonePage,
		PhoneCallComponent,
		PageErrorComponent,
		Page404Component,
		LoginPage,
		LoginHelpPage,
		SettingsPage,
		DashboardPage,
		RegisterPage,
		BlockListPage,
		ContactsPage,
		AccountPage,
		LoginShellComponent,
		HLoaderComponent,
		ContactSearchModalComponent,
		CapturePhotoModalComponent,
		ClickOutside,
		UploadPhotoMenuComponent,
		CallFailureModalComponent,
		DashboardHomeComponent,
		MaterialAlertComponent,
		MaterialActionAlertComponent,
		MaterialSnackBarComponent,
		mobileCollapse, //directive
		PbxRepLinesComponent,
		CompanyComponent,
		EmployeesComponent,
		PbxLinesComponent,
		CompanyOverviewComponent,
		CreateCompanyComponent,
		CreatePbxLineComponent,
		InviteEmployeeComponent, //causing problems
		CallQueueComponent,

		PbxLineCallComponent,
		PbxLineVideoComponent,
		PbxLineChatComponent,
		PbxLineQueueComponent,
		PbxLineInformationComponent,
		PbxCustomerComponent,

		PbxSearchBoxComponent,
		PbxRepShellComponent,
		PbxEmployersComponent,
		PbxSearchComponent,
		FileNamePipe,
		//IncomingCallDialogComponent,

		//PbxRepIncomingCallComponent,
		OutgoingCallDialogComponent,
		PbxLineOutgoingCallDialog,
		EmployeeCompaniesComponent,
		ShowFormErrorsComponent,
		MemberLoginFormComponent,
		GuestLoginFormComponent,
		LogoutPage,
		RegisterFormComponent,
		FooterComponent,
		ProfileSummaryComponent,
		NavMenuComponent,
		ContactUsPage,
		ContactUsFormComponent,
		MyCompanyPage,
		MyEmployersPage,
		ContactComponent,
		ContactListComponent,
		ButtonAddContactComponent,
		SidenavToggleComponent,
		FormAddContactComponent,
		ImageSelectorComponent,
		PhotoCameraComponent,
		FormEditContactComponent,
		ContactCardComponent,
		IdCardComponent,
		IncomingPhoneCallComponent,
		PhoneListenerComponent,
		GlobalListenerComponent,
		GlobalPhoneListenerComponent,
		FormCreateCompanyComponent,
		FormEditCompanyComponent,
		CompanyCreatePage,
		CompanyEditPage,
		CompanyEmployeeInvitesPage,
		CompanyEmployeesPage,
		CompanyLocationsComponent,
		CompanyPbxlineDetailsComponent,
		CompanyPbxlineRepsComponent,
		CompanyPbxlinesPage,
		CompanyPhotosComponent,
		CompanyProfilePage,
		CompanyVideosComponent,
		EmployerAssignedPbxlineComponent,
		EmployerAssignedPbxlinesPage,
		EmployerDetailsComponent,
		FormCompanyEmployeeAddComponent,
		FormCompanyEmployeeEditComponent,
		FormCompanyEmployeeInviteAddComponent,
		FormCompanyEmployeeInviteEditComponent,
		FormCompanyLocationAddComponent,
		FormCompanyPbxlineAddComponent,
		FormCompanyPbxlineEditComponent,
		FormCompanyPhotoAddComponent,
		FormCompanyVideoAddComponent,
		FormCompanyPbxlineRepAddComponent,
		CompanyPhotoComponent,
		ButtonAddCompanyPhotoComponent,
		FormCompanyLocationEditComponent,
		ButtonAddCompanyLocationComponent,
		ButtonAddCompanyVideoComponent,
		ButtonAddEmployeeInviteComponent,
		ButtonAddPbxlineComponent,
		CompanyLocationComponent,
		CompanyPbxlineComponent,
		EmployeeCardComponent,
		CompanyEmployeeInviteComponent,
		PublicUserProfilePage,
		CompanyEmployeeDetailsPage,
		CompanyEmployeeComponent,
		PublicPbxlineComponent,
		CustomerPbxPage,
		RepPbxPage,
		PhoneRingerComponent,
		TextMessagingComponent,
		TextMessagingMessageComponent,
		PrivateMessagingComponent,
		CompanySearchPage,
		GuestAccountPage,
		PbxCustomerDetailsComponent,
		OtherRepsComponent,
		OtherRepComponent,
		FormGetInfoComponent,
		ManageMeetingsPage,
		MeetingsPage,
		MeetingInvitesPage,
		CreateMeetingPage,
		MeetingPage,
		MeetingsDashboardPage,
		MeetingAttendeeComponent,
		FormAddAttendeeComponent,
		MeetingItemComponent,
		FormEditMeetingComponent,
		MeetingDetailsComponent,
		MeetingInviteComponent,
		PastMeetingsPage,
		NetcasterPage,
		NetcasteePage,
		LoginOptionsComponent,
		NetcastListPage,
		FormNetcastAddComponent,
		FormNetcastEditComponent,
		ButtonAddNetcastComponent,
		NetcastSearchPage,
		NetcastDashboardPage,
		NetcastDetailsPage,
		ErrorPage,
	],

	imports: [
		RouterModule.forRoot(appRoutes, { useHash: true, enableTracing: false }),

	]
};